<?php

/**
 * Implementation of hook_menu
 */
function forena_pdf_menu() { 
  $items = array();
  $items['admin/config/content/forena/pdf'] = array(
    'title' => 'PDF', 
    'type' => MENU_LOCAL_TASK, 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('forena_pdf_configure'), 
    'access arguments' => array('administer forena reports'), 
  ); 
  return $items; 
}

/**
 * Implementation of hook_forena_document_types
 */
function forena_pdf_forena_document_types() { 
  require_once 'docformats/FrxPrincePDF.inc';
  $items = array(); 
  if (file_exists('sites/all/libraries/prince.php')) { 
    $items['pdf'] = array(
      'class' => 'FrxPrincePDF', 
      'title' => t('PDF Document'), 
    ); 
  }
  return $items; 
}

/**
 * Implementation of configuration form. 
 * @param unknown_type $formid
 * @param unknown_type $form_state
 */
function forena_pdf_configure($formid, &$form_state)  { 
  $path = variable_get('forena_pdf_prince_path', '/usr/local/bin/prince'); 
  $disable_links = variable_get('forena_pdf_disable_links', TRUE); 
  
  $form['forena_pdf_prince_path'] = array(
    '#type' => 'textfield',
    '#title' => 'Path to binary',
    '#description' => t('Specify the location of the prince executable (e.g. /usr/local/bin/prince'), 
    '#required' => TRUE,  
    '#default_value' => $path, 
  ); 
  
  $form['forena_pdf_disable_links'] = array(
    '#type' => 'checkbox',
    '#title' => ('Disable links in PDF Documents'), 
    '#description' => t('When checked links in reports will not appear as links in PDF documents.'), 
    '#default_value' => $disable_links, 
  ); 
  return $form; 
}

function forena_pdf_configure_validate($form, &$form_state) { 
  if (!file_exists($form_state['values']['forena_pdf_prince_path'])) { 
    form_set_error('fornena_pdf_prince_path', t('could Not find libary.  Is Prince installed in this location?')); 
  }
}

function forena_pdf_configure_submit($form, &$form_state) { 
  variable_set('forena_pdf_prince_path', $form_state['values']['forena_pdf_prince_path']); 
  variable_set('forena_pdf_disable_links', $form_state['values']['forena_pdf_disable_links']); 
  drupal_set_message(t('Options Saved')); 
}